name: spread_sheet
description: "Spreadsheet with editable cells"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  freezed_annotation: ^3.0.0
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  two_dimensional_scrollables: ^0.3.4

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  very_good_analysis: ^7.0.0

dependency_overrides:
  custom_lint_visitor: 1.0.0+7.3.0

flutter:
  uses-material-design: true
